version: '3.9'
services:
  db:
    container_name: yorkiebakery-api-db
    image: postgres:16.10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yorkiebakery
      PYTHONPATH: /app
      POSTGRES_INITDB_ARGS: "--locale=C --lc-ctype=C --lc-collate=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: yorkiebakery-api-web
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/yorkiebakery
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
